[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    # Forge std
    "forge-std/=lib/forge-std/src/",

    # v4-periphery mappings
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "v4-periphery/=lib/v4-periphery/",

    # v4-core, prioritize v4-periphery's bundled v4-core
    # as there seems to be a mismatch between versions
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "v4-core/=lib/v4-periphery/lib/v4-core/",

    # Universal router mappings
    "universal-router/=lib/universal-router/",

    #    v3 and v2 mappings (used by universal router)
    "@uniswap/v3-core/=lib/v3-core/",
    "v3-core/=lib/v3-core/",
    "@uniswap/v2-core/=lib/v2-core/",
    "v2-core/=lib/v2-core/",

    # Permit2 mappings
    "permit2/=lib/permit2/",
    "@uniswap/permit2/=lib/permit2/",

    #     Solmate (used by permit2)
    "solmate/=lib/solmate",

    # OpenZeppelin
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# v4 specific settings https://docs.uniswap.org/contracts/v4/quickstart/hooks/setup
solc_version = "0.8.26"
evm_version = "cancun"
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# lib/universal-router/contracts/modules/uniswap/v2/V2SwapRouter.sol:39:24 requires compilation with via_ir
# having 'too much' state variables seems to require it too
via_ir = true
# optimizer = true
# optimizer_runs = 200
